# -*- coding: utf-8 -*-
"""MyPart-POO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nazr5hD5ApWUIDl_cds7qH252n1DtBEY
"""

class Cliente(Entidade):
  def __init__(self, nome, telefone, endereco, cpf):
    self.nome = nome
    self.telefone = telefone
    self.endereco = endereco
    self.cpf = cpf

  """def nome_clt(self, nome):
    self.nome = nome

  def tel_clt(self, telefone):
    self.telefone = telefone

  def end_clt(self, endereco):
    self.endereco = endereco

  def cpf_clt(self, cpf):
    self.cpf = cpf"""

  def retorna_nome(self):
    return self.nome

  def retorna_tel(self):
    return self.telefone

  def retorna_end(self):
    return self.endereco
  
  def retorna_cpf(self):
    return self.cpf
